env:
  node: true
extends:
  - ../../.eslintrc.yml
  - plugin:react/recommended
plugins:
  - react
settings:
  react: {version: detect}
rules:
  react/prop-types: off
  '@typescript-eslint/camelcase': [error, {allow: ["^[A-Z]"]}]
