parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
  - import
  - prettier
  - mocha-no-only
extends:
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:prettier/recommended
settings:
  import/resolver:
    node:
      extensions: ['.js', '.jsx', '.ts', '.tsx']
rules:
  prefer-destructuring: off
  curly: [error, all]
  brace-style: [error, 1tbs, {allowSingleLine: false}]
  no-multiple-empty-lines: [error, {max: 1, maxEOF: 0, maxBOF: 0}]
  no-use-before-define: [error, {functions: false}]
  '@typescript-eslint/no-use-before-define': [error, {functions: false}]
  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/no-unused-vars': [error, {argsIgnorePattern: '^_', varsIgnorePattern: '^_'}]
  prefer-arrow-callback: off
  object-curly-spacing: [error, never]
  arrow-parens: [error, always]
  import/extensions: off
  import/prefer-default-export: off
  react/prop-types: off
  react/display-name: off
