extends:
  - stylelint-config-standard
plugins:
  - stylelint-scss
  - stylelint-order
rules:
  at-rule-no-unknown: null
  scss/at-rule-no-unknown: true
  color-hex-case: upper
  color-hex-length: long
  order/order:
    - custom-properties
    - declarations
  order/properties-alphabetical-order: true
  no-descending-specificity: null
